### ISSUE TITLE
Short a file name 'secrets.json'

### ISSUE THREAD

**Issue by Tdyh** [marcel-lagoda/blog-app#2]
when I colon your project  there is no 'secrets.json' in it . Could you plz help me with it

**Comment by Marcel176** [comment]
Hi there,
that file is missing on purpose as it contains sensitive project data & passwords. 
You can either:

1. Create your own `secrets.json` within main project folder. 
The file structure is as follows: 
```json
{
  "SECRET_KEY": "copy & paste your django secret key here",
  "NAME": "name of your database for that particular project",
  "PASSWORD": "your postgres password",
  "HOST": "enter your host (it should be enough to write 'localhost')",
  "USER": "enter a name of your database, default for postgresql is 'postgres'"
}
```
or 
2. Once you start up a new django project you can simply keep the SECRET_KEY variable as it is and for your database use SQLite which is default and requires no additional attention from your end. 

cheers,
Marcel

**Comment by Tdyh** [comment]
Oh my god . I should've thought about this , my bad,&nbsp; I'm a new one at this project . Thank you so much , I'm very appreciate this, you've been very helpful .




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MarcelLagoda"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 凌晨1:20
收件人: "marcel-lagoda/blog-app"<blog-app@noreply.github.com&gt;; 
抄送: "1328170476"<1328170476@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [marcel-lagoda/blog-app] Short a file name &#39;secrets.json&#39; (#2)





 
Hi there,
 that file is missing on purpose as it contains sensitive project data &amp; passwords.
 You can either:
  
Create your own secrets.json within main project folder.
 The file structure is as follows:
  {   "SECRET_KEY": "copy &amp; paste your django secret key here",   "NAME": "name of your database for that particular project",   "PASSWORD": "your postgres password",   "HOST": "enter your host (it should be enough to write 'localhost')",   "USER": "enter a name of your database, default for postgresql is 'postgres'" }
 
or
 2. Once you start up a new django project you can simply keep the SECRET_KEY variable as it is and for your database use SQLite which is default and requires no additional attention from your end.
 
cheers,
 Marcel

**Comment by marcel-lagoda** [comment]
hey, don't worry to much... it's ok you asked :)
